### PR TITLE
[ARM64_DYNAREC] Fixed a falsy optimization on PSHUFHW

### LINKED ISSUE #1342: Palworld Dedicated Server stopped loading
I believe some changes to box64 code during the last week have broken the compatibility with Palworld server.
Everything was working fine with the latest versions of v0.2.7, but now the server does not load and gets stuck in an endless loop when I try to load it. This is what I get from systemd logs:

```
Mar 07 06:16:41 oci-server systemd[1]: Started Palworld Server.
Mar 07 06:16:44 oci-server PalServer.sh[1775]: MessageBox: Message : Failed to read file ../../../Pal/Pal.uproject
Mar 07 06:16:45 oci-server PalServer.sh[1775]: Shutdown handler: initalize.
Mar 07 06:16:45 oci-server PalServer.sh[1775]: Increasing per-process limit of core file size to infinity.
Mar 07 06:16:45 oci-server PalServer.sh[1775]: OODLE ERROR : LZ corruption : DecodeOneQuantum fail!
Mar 07 06:16:45 oci-server PalServer.sh[1775]: OODLE ERROR : LZ corruption : OodleLZ_Decompress failed (0 != 5179)
Mar 07 06:16:45 oci-server PalServer.sh[1775]: Exiting abnormally (error code: 1)
Mar 07 06:16:45 oci-server systemd[1]: palworld.service: Deactivated successfully.
Mar 07 06:16:45 oci-server systemd[1]: palworld.service: Consumed 3.671s CPU time.
Mar 07 06:16:45 oci-server systemd[1]: palworld.service: Scheduled restart job, restart counter is at 4.
Mar 07 06:16:45 oci-server systemd[1]: Stopped Palworld Server.
Mar 07 06:16:45 oci-server systemd[1]: palworld.service: Consumed 3.671s CPU time.
Mar 07 06:16:45 oci-server systemd[1]: Started Palworld Server.
Mar 07 06:16:48 oci-server PalServer.sh[2158]: MessageBox: Message : Failed to read file ../../../Pal/Pal.uproject
Mar 07 06:16:48 oci-server PalServer.sh[2158]: Shutdown handler: initalize.
Mar 07 06:16:48 oci-server PalServer.sh[2158]: Increasing per-process limit of core file size to infinity.
Mar 07 06:16:48 oci-server PalServer.sh[2158]: OODLE ERROR : LZ corruption : DecodeOneQuantum fail!
Mar 07 06:16:48 oci-server PalServer.sh[2158]: OODLE ERROR : LZ corruption : OodleLZ_Decompress failed (0 != 5179)
Mar 07 06:16:48 oci-server PalServer.sh[2158]: Exiting abnormally (error code: 1)
Mar 07 06:16:48 oci-server systemd[1]: palworld.service: Deactivated successfully.
Mar 07 06:16:48 oci-server systemd[1]: palworld.service: Consumed 3.249s CPU time.
Mar 07 06:16:49 oci-server systemd[1]: palworld.service: Scheduled restart job, restart counter is at 5.
Mar 07 06:16:49 oci-server systemd[1]: Stopped Palworld Server.
Mar 07 06:16:49 oci-server systemd[1]: palworld.service: Consumed 3.249s CPU time.
```

I was using ryanfortner apt repository to update my package once or twice a week, so unfortunately I haven't tested all the daily releases and I don't know how to determine exactly which version ended up causing the issue.
Downgrading back to the latest v0.2.6 release solves the issue and the server loads normally as expected.
I'm running an OCI Ampere instance with ubuntu 22.04, by the way.
I can add additional info if someone could guide me into collecting others logs.
Thank you.

### PR DESCRIPTION
**Pull request by ksco**
`VDUP_16` duplicates 16-bit element from the low qword of v1, which is not what we want.

Fixes #1342

### CODE REVIEW

File: src/dynarec/arm64/dynarec_arm64_f30f.c [hunk 1]
```diff
@@ -334,19 +334,15 @@ uintptr_t dynarec64_F30F(dynarec_arm_t* dyn, uintptr_t addr, uintptr_t ip, int n
             GETGX(v0, 1);
             u8 = F8;
             d0 = fpu_get_scratch(dyn);
-            if(u8==0b00000000 || u8==0b01010101 || u8==0b10101010 || u8==0b11111111) {
-                VDUP_16(d0, v1, u8&3);
```
Comment (ptitSeb) [inline src/dynarec/arm64/dynarec_arm64_f30f.c:338]: Maybe it needs a `VMOVeD(d0, 0, v1, 1);` before than?

Comment (ksco) [reply src/dynarec/arm64/dynarec_arm64_f30f.c:338]: Ah we can do that?

Comment (ptitSeb) [reply src/dynarec/arm64/dynarec_arm64_f30f.c:338]: or a `VDUPQ_16(d0, v1, u8&3+4);`  directly?

Comment (ksco) [reply src/dynarec/arm64/dynarec_arm64_f30f.c:338]: The Q means high part?

Comment (ksco) [reply src/dynarec/arm64/dynarec_arm64_f30f.c:338]: But it should be `(u8&3) + 4)` IIUC, yes?

**Comment by ptitSeb** [comment]
thanks
