### PR TITLE
[ENV] Fixed crash when rcfile does not exist (for #2295)

### LINKED ISSUE #2295: Newer Box64 Broken on MiceWine
Starting from commit ```7099774a3c82642ad64bc3a4f1b798e951904f7d```

Box64 stopped to work on MiceWine

See logs:

```
[BOX64] Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS SHA1 SHA2
[BOX64] Running on ARM64 CPU with 8 cores, pagesize: 4096
[BOX64] Will use hardware counter measured at 19.2 MHz emulating 2.4 GHz
[BOX64] Wine64 detected, WINEPRELOADRESERVE=""
[BOX64] Didn't detect 48bits of address space, considering it's 39bits
[BOX64] Warning, program break not found
[BOX64] WINE prereserve of 0x10000:0x8000 done
[BOX64] WINE prereserve of 0x110000:0x30000000 done
[BOX64] WINE prereserve of 0x7f000000:0x3000000 done
[BOX64] Warning, older then 2.34 pthread_kill not found, using current one
[BOX64] Counted 65 Env var
[BOX64] BOX64 LIB PATH: 
[BOX64] BOX64 BIN PATH: ./:bin/:/product/bin/:/apex/com.android.runtime/bin/:/apex/com.android.art/bin/:/system_ext/bin/:/system/bin/:/system/xbin/:/odm/bin/:/vendor/bin/:/vendor/xbin/:/data/data/com.micewine.emu/files/usr/bin/:/data/data/com.micewine.emu/files/wine/bin/:/data/data/com.micewine.emu/files/packages/Box64-bc454ffd-6d8b-405f-97cf-a77d49f54863/files/usr/bin/
[BOX64] Looking for wine
[BOX64] BOX64ENV: Variables overridden via env and/or RC file:
	BOX64_DYNAREC_ALIGNED_ATOMICS=0
	BOX64_DYNAREC_BIGBLOCK=1
	BOX64_DYNAREC_BLEEDING_EDGE=1
	BOX64_DYNAREC_CALLRET=1
	BOX64_DYNAREC_DIRTY=0
	BOX64_DYNAREC_FASTNAN=0
	BOX64_DYNAREC_FASTROUND=1
	BOX64_DYNAREC_NATIVEFLAGS=1
	BOX64_DYNAREC_PAUSE=0
	BOX64_DYNAREC_SAFEFLAGS=0
	BOX64_DYNAREC_STRONGMEM=1
	BOX64_DYNAREC_WAIT=1
	BOX64_DYNAREC_WEAKBARRIER=1
	BOX64_DYNAREC_X87DOUBLE=0
	BOX64_LOG=1
	BOX64_NOSIGSEGV=0
	BOX64_NOSIGILL=0
	BOX64_RCFILE=/data/data/com.micewine.emu/files/usr/etc/box64.box64rc
	BOX64_SHOWBT=0
	BOX64_SHOWSEGV=0
	BOX64_AVX=0
	BOX64_MMAP32=1
[BOX64] argv[1]="explorer"
[BOX64] argv[2]="/desktop=shell,960x540"
[BOX64] argv[3]="window_handler"
[BOX64] argv[4]="TFM"
[BOX64] Rename process to "wine"
[BOX64] Warning, program break not found
[BOX64] Using native(wrapped) libdl.so
[BOX64] Warning, program break not found
[BOX64] Using native(wrapped) libc.so
[BOX64] Warning, program break not found
[BOX64] Using native(wrapped) libpthread.so
[BOX64] Using native(wrapped) libm.so
[BOX64] Using native(wrapped) libbsd.so
[BOX64] Warning, program break not found
[BOX64] Using emulated /data/data/com.micewine.emu/files/wine/bin/../lib/wine/x86_64-unix/ntdll.so
[BOX64] Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS SHA1 SHA2
[BOX64] Running on ARM64 CPU with 8 cores, pagesize: 4096
[BOX64] Will use hardware counter measured at 19.2 MHz emulating 2.4 GHz
[BOX64] Wine preloader detected, loading "/data/data/com.micewine.emu/files/wine/lib/wine/../../bin/wine" directly
[BOX64] Wine64 detected, WINEPRELOADRESERVE=""
[BOX64] Didn't detect 48bits of address space, considering it's 39bits
[BOX64] Warning, program break not found
[BOX64] WINE prereserve of 0x10000:0x8000 done
[BOX64] WINE prereserve of 0x110000:0x30000000 done
[BOX64] WINE prereserve of 0x7f000000:0x3000000 done
[BOX64] Warning, older then 2.34 pthread_kill not found, using current one
[BOX64] Counted 67 Env var
[BOX64] BOX64 LIB PATH: 
[BOX64] BOX64 BIN PATH: ./:bin/:/product/bin/:/apex/com.android.runtime/bin/:/apex/com.android.art/bin/:/system_ext/bin/:/system/bin/:/system/xbin/:/odm/bin/:/vendor/bin/:/vendor/xbin/:/data/data/com.micewine.emu/files/usr/bin/:/data/data/com.micewine.emu/files/wine/bin/:/data/data/com.micewine.emu/files/packages/Box64-bc454ffd-6d8b-405f-97cf-a77d49f54863/files/usr/bin/
[BOX64] Looking for /data/data/com.micewine.emu/files/wine/lib/wine/../../bin/wine
[BOX64] BOX64ENV: Variables overridden via env and/or RC file:
	BOX64_DYNAREC_ALIGNED_ATOMICS=0
	BOX64_DYNAREC_BIGBLOCK=1
	BOX64_DYNAREC_BLEEDING_EDGE=1
	BOX64_DYNAREC_CALLRET=1
	BOX64_DYNAREC_DIRTY=0
	BOX64_DYNAREC_FASTNAN=0
	BOX64_DYNAREC_FASTROUND=1
	BOX64_DYNAREC_NATIVEFLAGS=1
	BOX64_DYNAREC_PAUSE=0
	BOX64_DYNAREC_SAFEFLAGS=0
	BOX64_DYNAREC_STRONGMEM=1
	BOX64_DYNAREC_WAIT=1
	BOX64_DYNAREC_WEAKBARRIER=1
	BOX64_DYNAREC_X87DOUBLE=0
	BOX64_LOG=1
	BOX64_NOSIGSEGV=0
	BOX64_NOSIGILL=0
	BOX64_RCFILE=/data/data/com.micewine.emu/files/usr/etc/box64.box64rc
	BOX64_SHOWBT=0
	BOX64_SHOWSEGV=0
	BOX64_AVX=0
	BOX64_MMAP32=1
[BOX64] argv[1]="explorer"
[BOX64] argv[2]="/desktop=shell,960x540"
[BOX64] argv[3]="window_handler"
[BOX64] argv[4]="TFM"
[BOX64] Rename process to "wine"
[BOX64] Warning, program break not found
[BOX64] Using native(wrapped) libdl.so
[BOX64] Warning, program break not found
[BOX64] Using native(wrapped) libc.so
[BOX64] Warning, program break not found
[BOX64] Using native(wrapped) libpthread.so
[BOX64] Using native(wrapped) libm.so
[BOX64] Using native(wrapped) libbsd.so
[BOX64] Warning, program break not found
[BOX64] Using emulated /data/data/com.micewine.emu/files/wine/bin/../lib/wine/x86_64-unix/ntdll.so
[BOX64] posix_spawn(0x76f2a58398, "/data/data/com.micewine.emu/files/wine/lib/wine/../../bin/wineserver", 0x0, 0x0, 0x76f2a583a0["/data/data/com.micewine.emu/files/wine/lib/wine/../../bin/wineserver", "", ...], 0x76f2a58730), IsX64=1, IsX86=0 IsScript=0 envp is context->envv
[BOX64]  => posix_spawn(0x76f2a58398, "/data/data/com.micewine.emu/files/packages/Box64-bc454ffd-6d8b-405f-97cf-a77d49f54863/files/usr/bin/box64", 0x0, 0x0, 0x7fd725ce50 ["/data/data/com.micewine.emu/files/packages/Box64-bc454ffd-6d8b-405f-97cf-a77d49f54863/files/usr/bin/box64", "/data/data/com.micewine.emu/files/wine/lib/wine/../../bin/wineserver", ""...:1], 0x7fd725d568)
[BOX64] posix_spawn returned 0
[BOX64] Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS SHA1 SHA2
[BOX64] Running on ARM64 CPU with 8 cores, pagesize: 4096
[BOX64] Will use hardware counter measured at 19.2 MHz emulating 2.4 GHz
[BOX64] Didn't detect 48bits of address space, considering it's 39bits
[BOX64] Warning, program break not found
[BOX64] Warning, older then 2.34 pthread_kill not found, using current one
[BOX64] Counted 67 Env var
[BOX64] BOX64 LIB PATH: 
[BOX64] BOX64 BIN PATH: ./:bin/:/product/bin/:/apex/com.android.runtime/bin/:/apex/com.android.art/bin/:/system_ext/bin/:/system/bin/:/system/xbin/:/odm/bin/:/vendor/bin/:/vendor/xbin/:/data/data/com.micewine.emu/files/usr/bin/:/data/data/com.micewine.emu/files/wine/bin/:/data/data/com.micewine.emu/files/packages/Box64-bc454ffd-6d8b-405f-97cf-a77d49f54863/files/usr/bin/
[BOX64] Looking for /data/data/com.micewine.emu/files/wine/lib/wine/../../bin/wineserver
[BOX64] BOX64ENV: Variables overridden via env and/or RC file:
	BOX64_DYNAREC_ALIGNED_ATOMICS=0
	BOX64_DYNAREC_BIGBLOCK=1
	BOX64_DYNAREC_BLEEDING_EDGE=1
	BOX64_DYNAREC_CALLRET=1
	BOX64_DYNAREC_DIRTY=0
	BOX64_DYNAREC_FASTNAN=0
	BOX64_DYNAREC_FASTROUND=1
	BOX64_DYNAREC_NATIVEFLAGS=1
	BOX64_DYNAREC_PAUSE=0
	BOX64_DYNAREC_SAFEFLAGS=0
	BOX64_DYNAREC_STRONGMEM=1
	BOX64_DYNAREC_WAIT=1
	BOX64_DYNAREC_WEAKBARRIER=1
	BOX64_DYNAREC_X87DOUBLE=0
	BOX64_LOG=1
	BOX64_NOSIGSEGV=0
	BOX64_NOSIGILL=0
	BOX64_RCFILE=/data/data/com.micewine.emu/files/usr/etc/box64.box64rc
	BOX64_SHOWBT=0
	BOX64_SHOWSEGV=0
	BOX64_AVX=0
	BOX64_MMAP32=1
[BOX64] Rename process to "wineserver"
[BOX64] Warning, program break not found
[BOX64] Using native(wrapped) libdl.so
[BOX64] Warning, program break not found
[BOX64] Using native(wrapped) libc.so
[BOX64] Warning, program break not found
[BOX64] Using native(wrapped) libpthread.so
[BOX64] Using native(wrapped) libm.so
[BOX64] Using native(wrapped) libbsd.so
wine client error:0: recvmsg: Connection reset by peer
```

### PR DESCRIPTION
**Pull request by ksco**
Fixed #2295

### CODE REVIEW

File: src/tools/env.c [hunk 1]
```diff
@@ -569,7 +570,7 @@ void RecordEnvMappings(uintptr_t addr, size_t length, int fd)
     int ret;
     mapping_t* mapping = NULL;
```
Comment (ptitSeb) [inline src/tools/env.c:571]: why not testing for mapping_entry here, and don't do the search if it's NULL, so we avoid creating the hash for nothing?

Comment (ksco) [reply src/tools/env.c:569]: Done

Comment (ptitSeb) [reply src/tools/env.c:569]: I was more thinking of putting lines 571-590 behind a `if(mapping_entries) { ... }` but it doesn't matter much actualy.
